[package]
name = "atm"
version = "0.1.0"
edition = "2018"

[dependencies]
rust_decimal = "1.15"
thiserror = "1.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
structopt = {version = "0.3", default-features = false }

